import React from 'react'
import { Box, Heading, useColorModeValue, Text, SimpleGrid, Image, HStack, Spacer } from '@chakra-ui/react';
import ImageDivider from './ImageDivider';


import eye from '../images/rarity/eyes1.png'
import hat from '../images/rarity/hat1.png'
import head from '../images/rarity/head1.png'
import mouth from '../images/rarity/mouth1.png'
import outfit from '../images/rarity/outfit1.png'
import outfit2 from '../images/rarity/outfit2.png'


function TraitCategory({ number, name, color, alt_color, src }) {
    return (
        <>
            <Box
                bg={color}
                rounded="12px"
                shadow='lg'
                px={10}
                _hover={{
                    boxShadow: 'inner'
                }}
            >
                <HStack>

                    <Box align="left">
                        <Heading size='md' color={alt_color}>
                            {number}
                        </Heading>
                        <Text size="md">
                            {name}
                        </Text>
                    </Box>

                    <Spacer />
                    <Image w='120px' pl={2} rounded='12px' justifySelf='flex-start' src={src} />
                </HStack>
            </Box>
        </>
    )
}


function Rarity() {
    const bg = useColorModeValue('light.blue', 'dark.blue')
    return (
        <>
            <Box backgroundColor={bg} align="center">
                <Box>
                    <Heading>Rarity</Heading>
                </Box>
                <Text py={8}>Each NFT is programatically generated by combining 240+ unique traits with varying rarity across categories.</Text>
                <Box w={['95%', '95%', '95%', '98%', '85%', '70%']}>
                    <Heading bgColor={useColorModeValue('white', '#2C2C2C')} shadow="lg" rounded="2xl" size='xl'>Trait Categories</Heading>
                    <SimpleGrid columns={[1, 1, 2, 3]} spacingX={[0, 0, 5, 10]} spacingY={10} py={12}>
                        <TraitCategory color="light.orange" alt_color="dark.orange" name="Body" number="71" src={outfit} />
                        <TraitCategory color="light.pink" alt_color="dark.pink" name="Background" number="20" src={outfit2} />
                        <TraitCategory color="light.green" alt_color="dark.green" name="Eyes" number="35" src={eye} />
                        <TraitCategory color="dark.blue" alt_color="light.blue" name="Hat" number="40" src={hat} />
                        <TraitCategory color="light.purple" alt_color="dark.purple" name="Head" number="26" src={head} />
                        <TraitCategory color="light.yellow" alt_color="dark.yellow" name="Mouth" number="12" src={mouth} />
                    </SimpleGrid>
                </Box>
            </Box>
            <ImageDivider
                fill_1={useColorModeValue('#BBEFFF', '#80B1FF')}
                fill_2={useColorModeValue('#FFD2EA', '#FFA4D4')}
                d="M0 111L14.5 109C29 107 58 103 87.2 97.8C116.3 92.7 145.7 86.3 174.8 96.8C204 107.3 233 134.7 262 140C291 145.3 320 128.7 349 125.5C378 122.3 407 132.7 436.2 130.3C465.3 128 494.7 113 523.8 101.3C553 89.7 582 81.3 611 86.2C640 91 669 109 698 123.7C727 138.3 756 149.7 785.2 151C814.3 152.3 843.7 143.7 872.8 137C902 130.3 931 125.7 945.5 123.3L960 121L960 201L945.5 201C931 201 902 201 872.8 201C843.7 201 814.3 201 785.2 201C756 201 727 201 698 201C669 201 640 201 611 201C582 201 553 201 523.8 201C494.7 201 465.3 201 436.2 201C407 201 378 201 349 201C320 201 291 201 262 201C233 201 204 201 174.8 201C145.7 201 116.3 201 87.2 201C58 201 29 201 14.5 201L0 201Z"
            />
        </>
    )
}

export default Rarity